import * as THREE from "three";
import { createScene } from "@render/scene";
import { TerrainMeshManager } from "@render/terrainMeshManager";
import { ClaimRingMeshManager } from "@render/claimRingMeshManager";
import { ElementMeshManager } from "@render/elementMeshManager";
import { HazardOverlayManager, FLOOD_OVERLAY_COLORS, CYCLONE_OVERLAY_COLORS } from "@render/floodOverlayManager";
import { GameState, type StartingElementSeed } from "@core/gameState";
import { ELEMENT_BY_ID } from "@core/elements";
import { axialToWorld, type AxialCoord } from "@core/hex";
import { resolveMonsoonFlood, resolveCyclone } from "@core/hazard";
import { computeEraScore } from "@core/scoring";
import { Hud } from "@ui/hud";
import { BuildPopover, type PopoverOption } from "@ui/buildPopover";
import { playSound } from "@ui/audioHooks";
import mapData from "@data/map.json";
import startingStateData from "@data/startingState.json";

interface MapFile {
  estuary: AxialCoord;
  startingClaim: AxialCoord[];
  tiles: { q: number; r: number; terrainId: string }[];
}
const MAP = mapData as MapFile;
const mapTiles = MAP.tiles.map((t) => ({ coord: { q: t.q, r: t.r }, terrainId: t.terrainId }));

interface StartingStateFile {
  startingCoin: number;
  startingPopulation: number;
  prebuiltHouses: AxialCoord[];
}
const STARTING_STATE = startingStateData as StartingStateFile;
const startingElements: StartingElementSeed[] = STARTING_STATE.prebuiltHouses.map((coord) => ({ coord, elementId: "house" }));

const container = document.getElementById("app")!;
const { scene, camera, renderer, start, focusOn, wasDrag } = createScene(container);

const terrain = new TerrainMeshManager();
const claimRing = new ClaimRingMeshManager();
const elements = new ElementMeshManager();
const floodOverlay = new HazardOverlayManager(FLOOD_OVERLAY_COLORS, "flood-overlay");
const cycloneOverlay = new HazardOverlayManager(CYCLONE_OVERLAY_COLORS, "cyclone-overlay");
scene.add(terrain.group);
scene.add(claimRing.mesh);
scene.add(elements.group);
scene.add(floodOverlay.mesh);
scene.add(cycloneOverlay.mesh);

/** A spinning storm marker over the coast — Section 5's "spinning storm icon approaching," in-scene, not text. */
const cycloneIcon = new THREE.Mesh(
  new THREE.TorusGeometry(0.6, 0.12, 6, 5),
  new THREE.MeshStandardMaterial({ color: "#3a3440", flatShading: true, roughness: 0.6 })
);
cycloneIcon.visible = false;
cycloneIcon.rotation.x = Math.PI / 2;
scene.add(cycloneIcon);

function keysToCoords(keys: Iterable<string>): AxialCoord[] {
  const coords: AxialCoord[] = [];
  for (const key of keys) {
    const [q, r] = key.split(",").map(Number);
    coords.push({ q, r });
  }
  return coords;
}

/**
 * v2.1 (Section 4): the terrain map is fixed and pre-generated by
 * /tools/mapgen, not player-drawn. `placed` holds the whole map from
 * construction; `claimed` is the player's growing footprint on it.
 */
const state = new GameState(mapTiles, MAP.startingClaim, startingElements, STARTING_STATE.startingCoin);
terrain.loadMap(mapTiles, keysToCoords(state.claimed));

// Section 4/8's new starting state: the player already owns a small
// residential cluster of pre-built Houses on Land, inland from the coastal
// claim — render them in place at boot, no settle animation (they were
// never "just built," they're already there).
for (const coord of STARTING_STATE.prebuiltHouses) {
  elements.place(coord, "house", terrain.heightAt(coord));
}

// Section 4/6: the fixed map's own (0,0) is an arbitrary point somewhere in
// the middle of a wide east-west strip — the player's actual starting
// cluster near the estuary can be far off in axial-coordinate space. Frame
// the camera on where play actually begins, not on the map's coordinate origin.
{
  const startWorld = MAP.startingClaim.reduce(
    (acc, c) => {
      const w = axialToWorld(c, 1.0);
      return { x: acc.x + w.x, z: acc.z + w.z };
    },
    { x: 0, z: 0 }
  );
  focusOn(startWorld.x / MAP.startingClaim.length, startWorld.z / MAP.startingClaim.length);
}

const hud = new Hud(container);
const buildPopover = new BuildPopover(container);

function refreshHud(): void {
  hud.setTileCount(state.claimed.size);
  hud.setCoin(state.coin);
  hud.setMeters({
    trust: state.trust,
    resilience: state.resilience,
    biodiversity: state.biodiversity,
    carbon: state.carbon,
    food: state.food,
    population: state.population
  });
  hud.setClaimable(state.claimableCount, 4);
}

refreshHud();

/** Projects a world position to CSS pixel coords within the canvas, for anchoring the build popover. */
function worldToScreen(x: number, y: number, z: number): { x: number; y: number } {
  const v = new THREE.Vector3(x, y, z).project(camera);
  const rect = renderer.domElement.getBoundingClientRect();
  return {
    x: ((v.x + 1) / 2) * rect.width,
    y: ((-v.y + 1) / 2) * rect.height
  };
}

function tilesOfType(...terrainIds: string[]): AxialCoord[] {
  const coords: AxialCoord[] = [];
  for (const tile of state.placed.values()) {
    if (terrainIds.includes(tile.terrainId)) coords.push(tile.coord);
  }
  return coords;
}

function applyHazardResult(
  result: { tileDamage: Map<string, number>; destroyedDefenses: string[]; overwhelmedDefenses: string[] },
  overlay: HazardOverlayManager,
  now: number
): void {
  for (const key of result.destroyedDefenses) {
    const [q, r] = key.split(",").map(Number);
    elements.destroy({ q, r });
  }
  for (const key of result.overwhelmedDefenses) {
    const inst = state.elements.get(key);
    if (!inst) continue;
    const [q, r] = key.split(",").map(Number);
    elements.setDegradeVisual({ q, r }, inst.degradeAmount);
  }
  for (const [key, damage] of result.tileDamage) {
    if (damage < 0.08) continue;
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    overlay.show(coord, terrain.heightAt(coord), damage, now);
  }
}

// --- Monsoon Flood telegraph + resolution ------------------------------------

const FLOOD_TELEGRAPH_COLOR = new THREE.Color("#0b2033");
const FLOOD_INTERVAL_TURNS = 15;
const FLOOD_TELEGRAPH_TURNS = 2;
let nextFloodAtTurn = FLOOD_INTERVAL_TURNS;

let floodTelegraphing = false;

function updateFloodTelegraph(): void {
  const turnsUntil = nextFloodAtTurn - state.turn;
  const telegraphing = turnsUntil > 0 && turnsUntil <= FLOOD_TELEGRAPH_TURNS;
  if (telegraphing && !floodTelegraphing) playSound("hazard_telegraph");
  floodTelegraphing = telegraphing;
  for (const coord of tilesOfType("river")) terrain.setTint(coord, telegraphing ? FLOOD_TELEGRAPH_COLOR : null);
}

/** Resolves the flood: visible in-scene (rising water, defenses absorbing/failing/degrading), not just meter numbers. */
function triggerFlood(baseSeverity: number): void {
  const result = resolveMonsoonFlood(state, baseSeverity);
  applyHazardResult(result, floodOverlay, performance.now());
  for (const coord of tilesOfType("river")) terrain.setTint(coord, null);
  floodTelegraphing = false;
  nextFloodAtTurn = state.turn + FLOOD_INTERVAL_TURNS;
  playSound("hazard_resolve");
  refreshHud();
  checkEraEnd();
}

// --- Cyclone telegraph + resolution -------------------------------------------

const CYCLONE_TELEGRAPH_COLOR = new THREE.Color("#3a3348");
const CYCLONE_INTERVAL_TURNS = 11;
const CYCLONE_TELEGRAPH_TURNS = 1; // fast — little warning, per Section 5
let nextCycloneAtTurn = CYCLONE_INTERVAL_TURNS;

function coastalCentroid(): { x: number; z: number } | null {
  const coords = tilesOfType("coast", "estuary");
  if (coords.length === 0) return null;
  let x = 0;
  let z = 0;
  for (const c of coords) {
    const w = axialToWorld(c, 1.0);
    x += w.x;
    z += w.z;
  }
  return { x: x / coords.length, z: z / coords.length };
}

let cycloneTelegraphing = false;

function updateCycloneTelegraph(): void {
  const turnsUntil = nextCycloneAtTurn - state.turn;
  const telegraphing = turnsUntil > 0 && turnsUntil <= CYCLONE_TELEGRAPH_TURNS;
  if (telegraphing && !cycloneTelegraphing) playSound("hazard_telegraph");
  cycloneTelegraphing = telegraphing;
  for (const coord of tilesOfType("coast", "estuary")) {
    terrain.setTint(coord, telegraphing ? CYCLONE_TELEGRAPH_COLOR : null, 0.45);
  }
  const centroid = coastalCentroid();
  cycloneIcon.visible = telegraphing && centroid !== null;
  if (telegraphing && centroid) cycloneIcon.position.set(centroid.x, 2.2, centroid.z);
}

/** Resolves the cyclone: wind+surge combined, Cyclone Shelter protecting Trust rather than land. */
function triggerCyclone(baseSeverity: number): void {
  const result = resolveCyclone(state, baseSeverity);
  applyHazardResult(result, cycloneOverlay, performance.now());
  for (const coord of tilesOfType("coast", "estuary")) terrain.setTint(coord, null);
  cycloneIcon.visible = false;
  cycloneTelegraphing = false;
  nextCycloneAtTurn = state.turn + CYCLONE_INTERVAL_TURNS;
  playSound("hazard_resolve");
  refreshHud();
  checkEraEnd();
}

// --- Era loop ------------------------------------------------------------------

/** Section 2: era soft-ends when Resilience hits zero — banked score, no hard game-over screen. */
function checkEraEnd(): void {
  if (!state.isEraOver) return;
  const score = Math.round(computeEraScore(state));
  const erasSoFar = state.erasCompleted + 1;
  playSound("era_end");
  hud.showBanner(`Era ${erasSoFar} retired — score ${score}. A new era begins.`);

  elements.reset();
  floodOverlay.reset();
  cycloneOverlay.reset();

  state.startNewEra(); // resets state.claimed back to the starting cluster + re-seeds the pre-built Houses
  terrain.resetClaims(keysToCoords(state.claimed));
  for (const coord of STARTING_STATE.prebuiltHouses) {
    elements.place(coord, "house", terrain.heightAt(coord));
  }
  nextFloodAtTurn = FLOOD_INTERVAL_TURNS;
  nextCycloneAtTurn = CYCLONE_INTERVAL_TURNS;

  claimRing.update([]);
  refreshHud();
}

/** Section 2: "a slowly rising monsoon intensity / cyclone season modifier" biases future severity upward within an era. */
function rolledSeverity(): number {
  return 1.0 + Math.random() * 0.6 + state.severityBaseline;
}

/** Claims any unclaimed hex (Section 2, v2.2: claim-anywhere, not adjacency-gated): costs Coin, reveals it, counts as a turn. */
function claimTile(coord: AxialCoord): boolean {
  if (!state.claim(coord)) return false;
  terrain.claimTile(coord);
  playSound("tile_settle");
  claimRing.update([]); // that tile is no longer claimable; the next pointermove will re-show hover state

  refreshHud();

  if (state.turn >= nextFloodAtTurn) triggerFlood(rolledSeverity());
  else updateFloodTelegraph();

  if (state.turn >= nextCycloneAtTurn) triggerCyclone(rolledSeverity());
  else updateCycloneTelegraph();

  return true;
}

// --- Build / defend popover --------------------------------------------------

/**
 * Section 3's "one tile, one element": a tile that already has something
 * built on it shows that element's info (name, category, effects) instead
 * of ever offering a second build menu — the UI should never let a player
 * attempt (or appear to attempt) building a second thing on an occupied tile.
 */
function openTilePopover(coord: AxialCoord): void {
  const key = `${coord.q},${coord.r}`;
  const worldTop = terrain.heightAt(coord);
  const { x: wx, z: wz } = axialToWorld(coord, 1.0);
  const screen = worldToScreen(wx, worldTop + 0.3, wz);

  const built = state.elements.get(key);
  if (built) {
    const def = ELEMENT_BY_ID.get(built.elementId);
    if (!def) return;
    buildPopover.showInfo(screen.x, screen.y, {
      name: def.name,
      kindLabel: def.kind === "building" ? "building" : def.category,
      effects: def.effects
    });
    return;
  }

  const options: PopoverOption[] = state
    .buildableAt(coord)
    .map((d) => ({ id: d.id, name: d.name, buildCost: d.buildCost, kindLabel: d.kind === "building" ? "building" : d.category }));
  if (options.length === 0) return;

  buildPopover.show(screen.x, screen.y, options, state.coin, (id) => {
    if (!state.build(coord, id)) return;
    elements.place(coord, id, terrain.heightAt(coord), { animate: true });
    playSound("build");
    refreshHud();
  });
}

// --- Input ---------------------------------------------------------------------
//
// Dismissal (NEXT_STEPS.md's A1): BuildPopover's own full-viewport backdrop
// now does the heavy lifting — while a popover is open, it physically sits
// above the canvas (and the HUD) and intercepts every click, so this
// canvas listener can no longer even fire for a "click elsewhere while a
// popover is open" case; the `isOpen` check below is a harmless leftover
// safety net, not the real mechanism anymore. No same-click
// close-and-reopen chains: a click that closes the popover is consumed by
// the backdrop and never reaches the raycast/claim/build logic below on
// that same click.

const raycaster = new THREE.Raycaster();
const pointer = new THREE.Vector2();

renderer.domElement.addEventListener("click", (event: MouseEvent) => {
  if (wasDrag()) return; // a pan, not a click — don't also claim/open a popover at the drag's end point
  if (buildPopover.isOpen) return; // shouldn't be reachable — the backdrop intercepts this click first

  const rect = renderer.domElement.getBoundingClientRect();
  pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
  pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

  raycaster.setFromCamera(pointer, camera);
  const hits = raycaster.intersectObjects(terrain.raycastTargets);
  if (hits.length === 0 || hits[0].instanceId === undefined) return;

  const coord = terrain.coordForHit(hits[0].object, hits[0].instanceId);
  if (!coord) return;

  const key = `${coord.q},${coord.r}`;
  if (state.claimed.has(key)) openTilePopover(coord);
  else if (state.isClaimable(coord)) claimTile(coord);
  // else: unreachable in practice under v2.2 (every unclaimed tile is
  // claimable), kept as a no-op guard rather than an assumption.
});

document.addEventListener("keydown", (event: KeyboardEvent) => {
  if (event.key === "Escape" && buildPopover.isOpen) buildPopover.hide();
});

/**
 * v2.2 (Section 2): claiming is no longer adjacency-gated, so there's no
 * single "frontier" for the game to point at. Instead, any unclaimed hex
 * should read as inviting via a hover affordance alone — a ring appears
 * under the cursor only while it's over a claimable tile.
 */
let hoveredClaimable: string | null = null;
renderer.domElement.addEventListener("pointermove", (event: MouseEvent) => {
  const rect = renderer.domElement.getBoundingClientRect();
  pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
  pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

  raycaster.setFromCamera(pointer, camera);
  const hits = raycaster.intersectObjects(terrain.raycastTargets);
  const coord = hits.length > 0 && hits[0].instanceId !== undefined
    ? terrain.coordForHit(hits[0].object, hits[0].instanceId)
    : null;

  const key = coord ? `${coord.q},${coord.r}` : null;
  const claimable = coord && state.isClaimable(coord) ? coord : null;
  const claimableKey = claimable ? key : null;
  if (claimableKey === hoveredClaimable) return;
  hoveredClaimable = claimableKey;

  claimRing.update(claimable ? [{ coord: claimable, topY: terrain.heightAt(claimable) }] : []);
});

start((nowMs) => {
  terrain.tick(nowMs);
  elements.tick(nowMs);
  floodOverlay.tick(nowMs);
  cycloneOverlay.tick(nowMs);
  claimRing.tick(nowMs);
  if (cycloneIcon.visible) cycloneIcon.rotation.z = nowMs * 0.003;
});

/**
 * Dev-only scenario helpers (Section 10: a hidden, non-UI debug overlay is
 * explicitly sanctioned for testing). Not part of the real UI — no button,
 * no visible affordance. Triggered only via URL params.
 */
function devAutoClaim(count: number): void {
  for (let i = 0; i < count; i++) {
    const next = mapTiles.find((t) => state.isClaimable(t.coord));
    if (!next) break;
    if (!claimTile(next.coord)) break; // out of coin — further attempts would just retry the same unaffordable tile
  }
}

/** Prefers an element type not yet built anywhere, so a dev screenshot shows variety rather than one type repeated. */
function devAutoBuild(kind: "building" | "defense"): void {
  const builtTypes = new Set<string>();
  for (const key of state.claimed) {
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    const options = state.buildableAt(coord).filter((o) => o.kind === kind);
    const affordable = options.filter((o) => o.buildCost <= state.coin);
    if (affordable.length === 0) continue;
    const pick = affordable.find((o) => !builtTypes.has(o.id)) ?? affordable[0];
    if (state.build(coord, pick.id)) {
      elements.place(coord, pick.id, terrain.heightAt(coord), { animate: true });
      builtTypes.add(pick.id);
    }
  }
  refreshHud();
}

// A tiny, always-present, inert-unless-called test hook — lets
// tools/verify_readability.ts (and any future script needing exact camera
// framing) pan straight to a world coordinate via the scene's own
// `focusOn`, instead of reverse-engineering the pan-drag pixel math. Costs
// nothing at runtime beyond one property assignment.
(window as unknown as Record<string, unknown>).__focusOnForTest = focusOn;

const params = new URLSearchParams(location.search);
// coinboost first: autoclaim/autobuild/autodefend below spend coin, so a
// boost given after them would arrive too late to fund what they just did.
const coinBoost = params.get("coinboost");
if (coinBoost) {
  state.coin += Number(coinBoost);
  refreshHud();
}
// Same reasoning as coinboost: needed before autoclaim below, since enough
// autoclaimed turns will otherwise trigger a real flood/cyclone and reset
// the era (via checkEraEnd) partway through a scripted scenario.
const resilienceBoost = params.get("resilienceboost");
if (resilienceBoost) {
  state.resilience += Number(resilienceBoost);
  refreshHud();
}
const autoclaimParam = params.get("autoclaim");
if (autoclaimParam) devAutoClaim(Number(autoclaimParam));
if (params.has("autobuild")) devAutoBuild("building");
if (params.has("autodefend")) devAutoBuild("defense");
const floodParam = params.get("flood");
if (floodParam) triggerFlood(Number(floodParam));
const cycloneParam = params.get("cyclone");
if (cycloneParam) triggerCyclone(Number(cycloneParam));

/** Dev-only: forces the popover open at a screen corner to verify Bucket A's viewport-clamping fix. */
if (params.has("testpopoverclip")) {
  const corner = params.get("testpopoverclip");
  const fakeOptions: PopoverOption[] = [
    { id: "a", name: "Test Option One", buildCost: 10 },
    { id: "b", name: "Test Option Two (Longer Name)", buildCost: 20 }
  ];
  const [x, y] =
    corner === "bottom-right"
      ? [window.innerWidth - 4, window.innerHeight - 4]
      : [4, 4];
  buildPopover.show(x, y, fakeOptions, 999, () => {});
}
