import * as THREE from "three";
import { createScene } from "@render/scene";
import { TerrainMeshManager } from "@render/terrainMeshManager";
import { ElementMeshManager } from "@render/elementMeshManager";
import { HazardOverlayManager, FLOOD_OVERLAY_COLORS, CYCLONE_OVERLAY_COLORS, type HazardKind } from "@render/floodOverlayManager";
import { CloudLayerManager } from "@render/cloudLayerManager";
import { GameState, type StartingElementSeed } from "@core/gameState";
import { ELEMENT_BY_ID, type ElementDef } from "@core/elements";
import { axialToWorld, type AxialCoord } from "@core/hex";
import { resolveMonsoonFlood, resolveCyclone, type HazardResult } from "@core/hazard";
import { computeEraScore } from "@core/scoring";
import { Hud } from "@ui/hud";
import { BuildPopover, type PopoverOption } from "@ui/buildPopover";
import { HazardTestPanel } from "@ui/hazardTestPanel";
import { playSound } from "@ui/audioHooks";
import mapData from "@data/map.json";
import startingStateData from "@data/startingState.json";

interface MapFile {
  estuary: AxialCoord;
  startingClaim: AxialCoord[];
  tiles: { q: number; r: number; terrainId: string }[];
}
const MAP = mapData as MapFile;
const mapTiles = MAP.tiles.map((t) => ({ coord: { q: t.q, r: t.r }, terrainId: t.terrainId }));

interface StartingStateFile {
  startingCoin: number;
  startingPopulation: number;
  prebuiltHouses: AxialCoord[];
}
const STARTING_STATE = startingStateData as StartingStateFile;
const startingElements: StartingElementSeed[] = STARTING_STATE.prebuiltHouses.map((coord) => ({ coord, elementId: "house" }));

const container = document.getElementById("app")!;
const { scene, camera, renderer, start, focusOn, wasDrag } = createScene(container);

// Declared this early (rather than down with the rest of Section 10's dev
// hooks) so the Test Hazards panel's own construction, below, can gate on
// it too — STEP_PROMPT_hazard_mechanics_fixes.md Bug 3: same "no visible
// affordance without an explicit URL param" bar every other dev tool here
// already holds itself to (see devAutoBuild's own comment further down).
const params = new URLSearchParams(location.search);

const terrain = new TerrainMeshManager();
const elements = new ElementMeshManager();
// STEP_PROMPT_hazard_science.md Section 6: one shared manager (not a
// separate instance per hazard type) so it can tell whether a tile is
// CURRENTLY showing the other hazard's overlay and blend to a genuine
// compound color — see floodOverlayManager.ts's own comment.
const hazardOverlay = new HazardOverlayManager(FLOOD_OVERLAY_COLORS, CYCLONE_OVERLAY_COLORS);
const cloudLayer = new CloudLayerManager();
scene.add(terrain.group);
scene.add(elements.group);
scene.add(hazardOverlay.mesh);
scene.add(cloudLayer.group);

/** A spinning storm marker over the coast — Section 5's "spinning storm icon approaching," in-scene, not text. */
const cycloneIcon = new THREE.Mesh(
  new THREE.TorusGeometry(0.6, 0.12, 6, 5),
  new THREE.MeshStandardMaterial({ color: "#3a3440", flatShading: true, roughness: 0.6 })
);
cycloneIcon.visible = false;
cycloneIcon.rotation.x = Math.PI / 2;
scene.add(cycloneIcon);

function keysToCoords(keys: Iterable<string>): AxialCoord[] {
  const coords: AxialCoord[] = [];
  for (const key of keys) {
    const [q, r] = key.split(",").map(Number);
    coords.push({ q, r });
  }
  return coords;
}

/**
 * v2.1 (Section 4): the terrain map is fixed and pre-generated by
 * /tools/mapgen, not player-drawn. `placed` holds the whole map.
 * STEP_PROMPT_remove_claiming.md: every tile is buildable from turn one —
 * `claimed` is no longer a growing player footprint, it's always exactly
 * `placed`.
 */
const state = new GameState(mapTiles, startingElements, STARTING_STATE.startingCoin);
terrain.loadMap(mapTiles, keysToCoords(state.claimed));

// Section 4/8's new starting state: the player already owns a small
// residential cluster of pre-built Houses on Land, inland from the coastal
// claim — render them in place at boot, no settle animation (they were
// never "just built," they're already there).
for (const coord of STARTING_STATE.prebuiltHouses) {
  elements.place(coord, "house", terrain.heightAt(coord));
}

// Section 4/6: the fixed map's own (0,0) is an arbitrary point somewhere in
// the middle of a wide east-west strip. `MAP.startingClaim` (still present
// in map.json, but no longer a claim gate — see STEP_PROMPT_remove_
// claiming.md) remains a convenient small coastal-cluster anchor to frame
// the camera on where play actually begins, not the map's coordinate origin.
{
  const startWorld = MAP.startingClaim.reduce(
    (acc, c) => {
      const w = axialToWorld(c, 1.0);
      return { x: acc.x + w.x, z: acc.z + w.z };
    },
    { x: 0, z: 0 }
  );
  focusOn(startWorld.x / MAP.startingClaim.length, startWorld.z / MAP.startingClaim.length);
}

const hud = new Hud(container);
const buildPopover = new BuildPopover(container);
/**
 * STEP_PROMPT_hazard_mechanics_fixes.md Bug 3: the same category of tool
 * as `devAutoBuild`/`?coinboost`/`?resilienceboost` — testing-only, not
 * meant for players — so it gets the same "no visible affordance without
 * the URL param" treatment those already have, instead of shipping as an
 * always-present button. `null` when the param is absent; every call site
 * below uses `?.`, so a normal visit constructs nothing extra at all.
 *
 * Calls straight into triggerCyclone/triggerFlood below (function
 * declarations — hoisted, safe to reference here) so a manual trigger
 * behaves exactly like a scheduled one in every way except where the
 * severity number came from — and, per Bug 2, except that it skips the
 * era-end check, so testing a hazard doesn't cost you the board you built
 * to test it on.
 */
const hazardTestPanel = params.has("debughazards")
  ? new HazardTestPanel(container, {
      onTriggerStorm: (severity) => triggerCyclone(severity, { skipEraCheck: true }),
      onTriggerFlood: (severity) => triggerFlood(severity, { skipEraCheck: true })
    })
  : null;

const YACHT_COST = ELEMENT_BY_ID.get("yacht")!.buildCost;

/**
 * STEP_PROMPT_hud_instrument_cluster.md: reads `nextCycloneAtTurn`/
 * `nextFloodAtTurn` (both `let` bindings declared later in this file) so
 * this — and therefore `refreshHud()` itself — can't safely run until
 * those exist. That's why `refreshHud()`'s own first call moved from
 * right after its definition (this file's old convention) to just past
 * the Cyclone section below, alongside `updateHazardTestSchedule()`'s
 * identical constraint.
 */
function hazardIncomingInfo(): { kind: "Storm Surge" | "Flood"; turnsUntil: number; imminent: boolean }[] {
  const stormTurnsUntil = nextCycloneAtTurn - state.turn;
  const floodTurnsUntil = nextFloodAtTurn - state.turn;
  const stormImminent = stormTurnsUntil > 0 && stormTurnsUntil <= CYCLONE_TELEGRAPH_TURNS;
  const floodImminent = floodTurnsUntil > 0 && floodTurnsUntil <= FLOOD_TELEGRAPH_TURNS;

  // Once at least one hazard is genuinely imminent (same condition the
  // terrain-tint/cloud telegraph already use), show every imminent
  // hazard's own line, urgent — never collapsed to one, since a compound
  // event (both imminent at once) is exactly the case worth surfacing
  // clearly, not hiding.
  if (stormImminent || floodImminent) {
    const lines: { kind: "Storm Surge" | "Flood"; turnsUntil: number; imminent: boolean }[] = [];
    if (stormImminent) lines.push({ kind: "Storm Surge", turnsUntil: stormTurnsUntil, imminent: true });
    if (floodImminent) lines.push({ kind: "Flood", turnsUntil: floodTurnsUntil, imminent: true });
    return lines;
  }

  // Neither imminent yet — a single neutral line for whichever is closer.
  return stormTurnsUntil <= floodTurnsUntil
    ? [{ kind: "Storm Surge", turnsUntil: stormTurnsUntil, imminent: false }]
    : [{ kind: "Flood", turnsUntil: floodTurnsUntil, imminent: false }];
}

function refreshHud(): void {
  hud.setTileCount(state.claimed.size);
  hud.setCoin(state.coin);
  hud.setMeters({
    resilience: state.resilience,
    biodiversity: state.biodiversity,
    carbon: state.carbon,
    food: state.food,
    population: state.population
  });
  hud.setHazardIncoming(hazardIncomingInfo());
  hud.setEmptyTiles(state.emptyTileCount);
  hud.setYachtGoal(state.coin, YACHT_COST, state.hasElement("yacht"));
}

/** Projects a world position to CSS pixel coords within the canvas, for anchoring the build popover. */
function worldToScreen(x: number, y: number, z: number): { x: number; y: number } {
  const v = new THREE.Vector3(x, y, z).project(camera);
  const rect = renderer.domElement.getBoundingClientRect();
  return {
    x: ((v.x + 1) / 2) * rect.width,
    y: ((-v.y + 1) / 2) * rect.height
  };
}

function tilesOfType(...terrainIds: string[]): AxialCoord[] {
  const coords: AxialCoord[] = [];
  for (const tile of state.placed.values()) {
    if (terrainIds.includes(tile.terrainId)) coords.push(tile.coord);
  }
  return coords;
}

// STEP_PROMPT_hazard_science.md Section 6: how long one BFS round gets on
// screen before the next round's tiles light up — ported from khazan_
// hazard_prototype.html's HOP_DURATION. PLACEHOLDER, same "flag it, let
// balance/feel tuning refine it" convention as every other number here.
const ROUND_DURATION_MS = 550;

/**
 * Applies a resolved hazard's game-state side effects immediately (defense
 * destruction/degrade visuals), then reveals each damaged tile's overlay
 * staggered by `result.arrivalRound` — so the sweep visually matches the
 * real hop-by-hop BFS resolution (Section 6 item 1/2) instead of every
 * damaged tile popping in at once regardless of how far it was from the
 * source.
 */
function applyHazardResult(kind: HazardKind, result: HazardResult, now: number): void {
  for (const key of result.destroyedDefenses) {
    const [q, r] = key.split(",").map(Number);
    elements.destroy({ q, r });
  }
  for (const key of result.overwhelmedDefenses) {
    const inst = state.elements.get(key);
    if (!inst) continue;
    const [q, r] = key.split(",").map(Number);
    elements.setDegradeVisual({ q, r }, inst.degradeAmount);
  }
  for (const [key, damage] of result.tileDamage) {
    if (damage < 0.08) continue;
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    const delayMs = (result.arrivalRound.get(key) ?? 0) * ROUND_DURATION_MS;
    if (delayMs <= 0) hazardOverlay.show(kind, coord, terrain.heightAt(coord), damage, now);
    else setTimeout(() => hazardOverlay.show(kind, coord, terrain.heightAt(coord), damage, performance.now()), delayMs);
  }
}

// --- Monsoon Flood telegraph + resolution ------------------------------------

const FLOOD_TELEGRAPH_COLOR = new THREE.Color("#0b2033");
const FLOOD_INTERVAL_TURNS = 15;
const FLOOD_TELEGRAPH_TURNS = 2;
let nextFloodAtTurn = FLOOD_INTERVAL_TURNS;

let floodTelegraphing = false;

/** Section 6 item 3: the cloud layer telegraphs either hazard, independent of the HUD/terrain-tint telegraph. */
function updateCloudVisibility(): void {
  cloudLayer.setVisible(floodTelegraphing || cycloneTelegraphing);
}

function updateFloodTelegraph(): void {
  const turnsUntil = nextFloodAtTurn - state.turn;
  const telegraphing = turnsUntil > 0 && turnsUntil <= FLOOD_TELEGRAPH_TURNS;
  if (telegraphing && !floodTelegraphing) playSound("hazard_telegraph");
  floodTelegraphing = telegraphing;
  for (const coord of tilesOfType("river")) terrain.setTint(coord, telegraphing ? FLOOD_TELEGRAPH_COLOR : null);
  updateCloudVisibility();
  updateHazardTestSchedule();
}

/**
 * STEP_PROMPT_hazard_science.md Section 5: the compound mechanic isn't just
 * calendar overlap (both hazards already trigger on independent schedules
 * and can coincidentally land close together, unchanged) — it's the Flood
 * resolver actually checking whether a Storm Surge Wave is concurrently
 * active before adding its downstream/tidal-push source (Section 3).
 * "Concurrently active" is generous on purpose: currently telegraphing (a
 * surge visibly imminent) OR resolved within the last couple of turns
 * (its surge is still realistically working through the system) both
 * count — not just "resolving on the exact same turn."
 */
const STORM_SURGE_COMPOUND_WINDOW_TURNS = 2;

/**
 * Resolves the flood: visible in-scene (rising water, defenses absorbing/
 * failing/degrading), not just meter numbers.
 *
 * STEP_PROMPT_hazard_mechanics_fixes.md Bug 2: `skipEraCheck` exists
 * purely for the Test Hazards panel and the `?flood=` dev param — a
 * manually-fired hazard that happens to cross Resilience to zero
 * shouldn't wipe the board the player is testing against. The hazard
 * still resolves fully (damage, absorption, meter changes, the visual
 * sweep); only the era-reset *consequence* is suppressed, and only on
 * this path. The two real call sites (`checkHazardSchedule()`'s scheduled
 * firing, `openTilePopover()`'s post-build check) never set it, so a
 * genuinely-scheduled hazard still ends an era exactly as before.
 */
function triggerFlood(baseSeverity: number, options: { skipEraCheck?: boolean } = {}): void {
  const stormSurgeActive = cycloneTelegraphing || state.turn - lastStormSurgeResolvedTurn <= STORM_SURGE_COMPOUND_WINDOW_TURNS;
  const result = resolveMonsoonFlood(state, baseSeverity, stormSurgeActive);
  applyHazardResult("flood", result, performance.now());
  for (const coord of tilesOfType("river")) terrain.setTint(coord, null);
  floodTelegraphing = false;
  updateCloudVisibility();
  nextFloodAtTurn = state.turn + FLOOD_INTERVAL_TURNS;
  updateHazardTestSchedule();
  playSound("hazard_resolve");
  refreshHud();
  if (!options.skipEraCheck) checkEraEnd();
}

// --- Cyclone telegraph + resolution -------------------------------------------

const CYCLONE_TELEGRAPH_COLOR = new THREE.Color("#3a3348");
const CYCLONE_INTERVAL_TURNS = 11;
const CYCLONE_TELEGRAPH_TURNS = 1; // fast — little warning, per Section 5
let nextCycloneAtTurn = CYCLONE_INTERVAL_TURNS;

function coastalCentroid(): { x: number; z: number } | null {
  const coords = tilesOfType("coast", "estuary");
  if (coords.length === 0) return null;
  let x = 0;
  let z = 0;
  for (const c of coords) {
    const w = axialToWorld(c, 1.0);
    x += w.x;
    z += w.z;
  }
  return { x: x / coords.length, z: z / coords.length };
}

let cycloneTelegraphing = false;
/** Section 5's compound-mechanic window (see STORM_SURGE_COMPOUND_WINDOW_TURNS above) — the turn a Storm Surge Wave last actually resolved, so a Flood shortly after still counts as concurrent. */
let lastStormSurgeResolvedTurn = -Infinity;

function updateCycloneTelegraph(): void {
  const turnsUntil = nextCycloneAtTurn - state.turn;
  const telegraphing = turnsUntil > 0 && turnsUntil <= CYCLONE_TELEGRAPH_TURNS;
  if (telegraphing && !cycloneTelegraphing) playSound("hazard_telegraph");
  cycloneTelegraphing = telegraphing;
  for (const coord of tilesOfType("coast", "estuary")) {
    terrain.setTint(coord, telegraphing ? CYCLONE_TELEGRAPH_COLOR : null, 0.45);
  }
  const centroid = coastalCentroid();
  cycloneIcon.visible = telegraphing && centroid !== null;
  if (telegraphing && centroid) cycloneIcon.position.set(centroid.x, 2.2, centroid.z);
  updateCloudVisibility();
  updateHazardTestSchedule();
}

/** Resolves the cyclone: wind+surge combined, Cyclone Shelter protecting Trust rather than land. `skipEraCheck` — see triggerFlood's own comment (Bug 2). */
function triggerCyclone(baseSeverity: number, options: { skipEraCheck?: boolean } = {}): void {
  const result = resolveCyclone(state, baseSeverity);
  applyHazardResult("storm", result, performance.now());
  for (const coord of tilesOfType("coast", "estuary")) terrain.setTint(coord, null);
  cycloneIcon.visible = false;
  cycloneTelegraphing = false;
  updateCloudVisibility();
  lastStormSurgeResolvedTurn = state.turn;
  nextCycloneAtTurn = state.turn + CYCLONE_INTERVAL_TURNS;
  updateHazardTestSchedule();
  playSound("hazard_resolve");
  refreshHud();
  if (!options.skipEraCheck) checkEraEnd();
}

/**
 * STEP_PROMPT_hazard_test_sliders.md's nice-to-have: orients whoever's
 * testing without them needing to wait out the schedule. Kept as its own
 * function (not folded into `refreshHud()`, unlike `hazardIncomingInfo()`
 * above) purely because the Test Hazards panel is optional (`null` unless
 * `?debughazards` is set) — folding an always-needed `?.`-guarded call
 * into every `refreshHud()` invocation is fine either way, but keeping it
 * separate here means `refreshHud()` itself never needs to know the panel
 * might not exist.
 */
function updateHazardTestSchedule(): void {
  hazardTestPanel?.setScheduleInfo(nextCycloneAtTurn - state.turn, nextFloodAtTurn - state.turn);
}
updateHazardTestSchedule();

// Both this and `hazardIncomingInfo()` (called from inside `refreshHud()`)
// need `nextFloodAtTurn`/`nextCycloneAtTurn` to already exist — this is
// the first point in the file where that's guaranteed, so `refreshHud()`'s
// very first call lives here now, not right after its own definition.
refreshHud();

// --- Era loop ------------------------------------------------------------------

/** Section 2: era soft-ends when Resilience hits zero — banked score, no hard game-over screen. */
function checkEraEnd(): void {
  if (!state.isEraOver) return;
  const score = Math.round(computeEraScore(state));
  const erasSoFar = state.erasCompleted + 1;
  playSound("era_end");
  hud.showBanner(`Era ${erasSoFar} retired — score ${score}. A new era begins.`);

  elements.reset();
  hazardOverlay.reset();
  hazardTestPanel?.reset(); // STEP_PROMPT_hazard_test_sliders.md's Verify: panel state doesn't need to persist across an era reset

  state.startNewEra(); // clears built elements (re-seeding the pre-built Houses) — state.claimed stays every tile, same as always now
  terrain.resetClaims(keysToCoords(state.claimed));
  for (const coord of STARTING_STATE.prebuiltHouses) {
    elements.place(coord, "house", terrain.heightAt(coord));
  }
  nextFloodAtTurn = FLOOD_INTERVAL_TURNS;
  nextCycloneAtTurn = CYCLONE_INTERVAL_TURNS;
  updateHazardTestSchedule();

  refreshHud();
}

/** Section 2: "a slowly rising monsoon intensity / cyclone season modifier" biases future severity upward within an era. */
function rolledSeverity(): number {
  return 1.0 + Math.random() * 0.6 + state.severityBaseline;
}

/**
 * STEP_PROMPT_remove_claiming.md: Build is now the sole action that
 * advances a turn (Claim used to own this job, including this check) —
 * called once after any successful `state.build()`, so a hazard fires (or
 * its telegraph updates) the moment the schedule's turn is actually
 * reached, regardless of which tile/element triggered it.
 */
function checkHazardSchedule(): void {
  if (state.turn >= nextFloodAtTurn) triggerFlood(rolledSeverity());
  else updateFloodTelegraph();

  if (state.turn >= nextCycloneAtTurn) triggerCyclone(rolledSeverity());
  else updateCycloneTelegraph();
}

// --- Build / defend popover --------------------------------------------------

/**
 * Small tag shown beside an element's name in its popover row. `category`
 * only exists on defense-kind elements — falling through to it for
 * anything else (as an earlier version of this ternary did) silently
 * printed "undefined" for Yacht's cosmetic kind once that was added
 * (STEP_PROMPT_economy_food_yacht.md item 4), since it has no category.
 */
function kindLabel(def: ElementDef): string | undefined {
  if (def.kind === "building" || def.kind === "cosmetic") return def.kind;
  return def.category;
}

/**
 * Section 3's "one tile, one element": a tile that already has something
 * built on it shows that element's info (name, category, effects) instead
 * of ever offering a second build menu — the UI should never let a player
 * attempt (or appear to attempt) building a second thing on an occupied tile.
 */
function openTilePopover(coord: AxialCoord): void {
  const key = `${coord.q},${coord.r}`;
  const worldTop = terrain.heightAt(coord);
  const { x: wx, z: wz } = axialToWorld(coord, 1.0);
  const screen = worldToScreen(wx, worldTop + 0.3, wz);

  const built = state.elements.get(key);
  if (built) {
    const def = ELEMENT_BY_ID.get(built.elementId);
    if (!def) return;
    buildPopover.showInfo(screen.x, screen.y, {
      name: def.name,
      kindLabel: kindLabel(def),
      effects: def.effects
    });
    return;
  }

  const options: PopoverOption[] = state
    .buildableAt(coord)
    .map((d) => ({ id: d.id, name: d.name, buildCost: d.buildCost, kindLabel: kindLabel(d) }));
  if (options.length === 0) return;

  buildPopover.show(screen.x, screen.y, options, state.coin, (id) => {
    if (!state.build(coord, id)) return;
    elements.place(coord, id, terrain.heightAt(coord), { animate: true });
    playSound("build");
    refreshHud();
    checkHazardSchedule();
    // A hazard resolving above already calls checkEraEnd() itself, but a
    // Food deficit alone (advanceTurn(), no hazard this turn) can also
    // drain Resilience to zero — check unconditionally so an era can't
    // silently end without the banner/reset firing. Idempotent: checkEraEnd
    // itself no-ops when the era isn't actually over.
    checkEraEnd();
  });
}

// --- Input ---------------------------------------------------------------------
//
// STEP_PROMPT_remove_claiming.md: every tile is already active — a click on
// any tile opens its popover directly (a build menu if empty, an info card
// if something's already standing there; see openTilePopover), no
// intermediate claim step. Dismissal (NEXT_STEPS.md's A1): BuildPopover's
// own full-viewport backdrop does the heavy lifting — while a popover is
// open, it physically sits above the canvas (and the HUD) and intercepts
// every click, so this canvas listener can no longer even fire for a
// "click elsewhere while a popover is open" case; the `isOpen` check below
// is a harmless leftover safety net, not the real mechanism anymore.

const raycaster = new THREE.Raycaster();
const pointer = new THREE.Vector2();

renderer.domElement.addEventListener("click", (event: MouseEvent) => {
  if (wasDrag()) return; // a pan, not a click — don't also open a popover at the drag's end point
  if (buildPopover.isOpen) return; // shouldn't be reachable — the backdrop intercepts this click first

  const rect = renderer.domElement.getBoundingClientRect();
  pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
  pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

  raycaster.setFromCamera(pointer, camera);
  const hits = raycaster.intersectObjects(terrain.raycastTargets);
  if (hits.length === 0 || hits[0].instanceId === undefined) return;

  const coord = terrain.coordForHit(hits[0].object, hits[0].instanceId);
  if (!coord) return;

  openTilePopover(coord);
});

document.addEventListener("keydown", (event: KeyboardEvent) => {
  if (event.key === "Escape" && buildPopover.isOpen) buildPopover.hide();
});

start((nowMs) => {
  terrain.tick(nowMs);
  elements.tick(nowMs);
  hazardOverlay.tick(nowMs);
  cloudLayer.tick(nowMs);
  if (cycloneIcon.visible) cycloneIcon.rotation.z = nowMs * 0.003;
});

/**
 * Dev-only scenario helpers (Section 10: a hidden, non-UI debug overlay is
 * explicitly sanctioned for testing). Not part of the real UI — no button,
 * no visible affordance. Triggered only via URL params.
 */

/** Prefers an element type not yet built anywhere, so a dev screenshot shows variety rather than one type repeated. */
function devAutoBuild(kind: "building" | "defense"): void {
  const builtTypes = new Set<string>();
  for (const key of state.claimed) {
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    const options = state.buildableAt(coord).filter((o) => o.kind === kind);
    const affordable = options.filter((o) => o.buildCost <= state.coin);
    if (affordable.length === 0) continue;
    const pick = affordable.find((o) => !builtTypes.has(o.id)) ?? affordable[0];
    if (state.build(coord, pick.id)) {
      elements.place(coord, pick.id, terrain.heightAt(coord), { animate: true });
      builtTypes.add(pick.id);
    }
  }
  refreshHud();
}

// A tiny, always-present, inert-unless-called test hook — lets
// tools/verify_readability.ts (and any future script needing exact camera
// framing) pan straight to a world coordinate via the scene's own
// `focusOn`, instead of reverse-engineering the pan-drag pixel math. Costs
// nothing at runtime beyond one property assignment.
(window as unknown as Record<string, unknown>).__focusOnForTest = focusOn;
// Same spirit as __focusOnForTest — a harmless, inert-unless-called hook so
// a verification script can force the cloud layer visible without waiting
// for a real telegraph window (turns only advance via build()).
(window as unknown as Record<string, unknown>).__cloudLayerForTest = cloudLayer;

// coinboost first: autobuild/autodefend below spend coin, so a boost given
// after them would arrive too late to fund what they just did.
const coinBoost = params.get("coinboost");
if (coinBoost) {
  state.coin += Number(coinBoost);
  refreshHud();
}
// Same reasoning as coinboost: needed before autobuild/autodefend below,
// since enough builds will otherwise trigger a real flood/cyclone and
// reset the era (via checkEraEnd) partway through a scripted scenario.
const resilienceBoost = params.get("resilienceboost");
if (resilienceBoost) {
  state.resilience += Number(resilienceBoost);
  refreshHud();
}
if (params.has("autobuild")) devAutoBuild("building");
if (params.has("autodefend")) devAutoBuild("defense");
// Bug 2: these are dev-only test fires (same category as the panel above),
// so they skip the era-end consequence too — a `?flood=3` link for a quick
// screenshot shouldn't reset the board any more than clicking the panel's
// own "Trigger now" should.
const floodParam = params.get("flood");
if (floodParam) triggerFlood(Number(floodParam), { skipEraCheck: true });
const cycloneParam = params.get("cyclone");
if (cycloneParam) triggerCyclone(Number(cycloneParam), { skipEraCheck: true });

/** Dev-only: forces the popover open at a screen corner to verify Bucket A's viewport-clamping fix. */
if (params.has("testpopoverclip")) {
  const corner = params.get("testpopoverclip");
  const fakeOptions: PopoverOption[] = [
    { id: "a", name: "Test Option One", buildCost: 10 },
    { id: "b", name: "Test Option Two (Longer Name)", buildCost: 20 }
  ];
  const [x, y] =
    corner === "bottom-right"
      ? [window.innerWidth - 4, window.innerHeight - 4]
      : [4, 4];
  buildPopover.show(x, y, fakeOptions, 999, () => {});
}
