import * as THREE from "three";
import { createScene } from "@render/scene";
import { TerrainMeshManager } from "@render/terrainMeshManager";
import { ClaimRingMeshManager } from "@render/claimRingMeshManager";
import { BuildingMeshManager } from "@render/buildingMeshManager";
import { DefenseMeshManager } from "@render/defenseMeshManager";
import { HazardOverlayManager, FLOOD_OVERLAY_COLORS, CYCLONE_OVERLAY_COLORS } from "@render/floodOverlayManager";
import { GameState } from "@core/gameState";
import { axialToWorld, type AxialCoord } from "@core/hex";
import { resolveMonsoonFlood, resolveCyclone } from "@core/hazard";
import { computeEraScore } from "@core/scoring";
import { Hud } from "@ui/hud";
import { BuildPopover, type PopoverOption } from "@ui/buildPopover";
import { playSound } from "@ui/audioHooks";
import mapData from "@data/map.json";

interface MapFile {
  estuary: AxialCoord;
  startingClaim: AxialCoord[];
  tiles: { q: number; r: number; terrainId: string }[];
}
const MAP = mapData as MapFile;
const mapTiles = MAP.tiles.map((t) => ({ coord: { q: t.q, r: t.r }, terrainId: t.terrainId }));

const container = document.getElementById("app")!;
const { scene, camera, renderer, start, focusOn } = createScene(container);

const terrain = new TerrainMeshManager();
const claimRing = new ClaimRingMeshManager();
const buildings = new BuildingMeshManager();
const defenses = new DefenseMeshManager();
const floodOverlay = new HazardOverlayManager(FLOOD_OVERLAY_COLORS, "flood-overlay");
const cycloneOverlay = new HazardOverlayManager(CYCLONE_OVERLAY_COLORS, "cyclone-overlay");
scene.add(terrain.group);
scene.add(claimRing.mesh);
scene.add(buildings.group);
scene.add(defenses.group);
scene.add(floodOverlay.mesh);
scene.add(cycloneOverlay.mesh);

/** A spinning storm marker over the coast — Section 5's "spinning storm icon approaching," in-scene, not text. */
const cycloneIcon = new THREE.Mesh(
  new THREE.TorusGeometry(0.6, 0.12, 6, 5),
  new THREE.MeshStandardMaterial({ color: "#3a3440", flatShading: true, roughness: 0.6 })
);
cycloneIcon.visible = false;
cycloneIcon.rotation.x = Math.PI / 2;
scene.add(cycloneIcon);

function keysToCoords(keys: Iterable<string>): AxialCoord[] {
  const coords: AxialCoord[] = [];
  for (const key of keys) {
    const [q, r] = key.split(",").map(Number);
    coords.push({ q, r });
  }
  return coords;
}

/**
 * v2.1 (Section 4): the terrain map is fixed and pre-generated by
 * /tools/mapgen, not player-drawn. `placed` holds the whole map from
 * construction; `claimed` is the player's growing footprint on it.
 */
const state = new GameState(mapTiles, MAP.startingClaim);
terrain.loadMap(mapTiles, keysToCoords(state.claimed));

// Section 4/6: the fixed map's own (0,0) is an arbitrary point somewhere in
// the middle of a wide east-west strip — the player's actual starting
// cluster near the estuary can be far off in axial-coordinate space. Frame
// the camera on where play actually begins, not on the map's coordinate origin.
{
  const startWorld = MAP.startingClaim.reduce(
    (acc, c) => {
      const w = axialToWorld(c, 1.0);
      return { x: acc.x + w.x, z: acc.z + w.z };
    },
    { x: 0, z: 0 }
  );
  focusOn(startWorld.x / MAP.startingClaim.length, startWorld.z / MAP.startingClaim.length);
}

const hud = new Hud(container);
const buildPopover = new BuildPopover(container);

function refreshClaimRing(): void {
  const claimable = state.claimFrontier().map((coord) => ({ coord, topY: terrain.heightAt(coord) }));
  claimRing.update(claimable);
  hud.setClaimable(claimable.length, 4);
}

function refreshHud(): void {
  hud.setTileCount(state.claimed.size);
  hud.setCoin(state.coin);
  hud.setMeters({
    trust: state.trust,
    resilience: state.resilience,
    biodiversity: state.biodiversity,
    carbon: state.carbon
  });
}

refreshClaimRing();
refreshHud();

/** Projects a world position to CSS pixel coords within the canvas, for anchoring the build popover. */
function worldToScreen(x: number, y: number, z: number): { x: number; y: number } {
  const v = new THREE.Vector3(x, y, z).project(camera);
  const rect = renderer.domElement.getBoundingClientRect();
  return {
    x: ((v.x + 1) / 2) * rect.width,
    y: ((-v.y + 1) / 2) * rect.height
  };
}

function tilesOfType(...terrainIds: string[]): AxialCoord[] {
  const coords: AxialCoord[] = [];
  for (const tile of state.placed.values()) {
    if (terrainIds.includes(tile.terrainId)) coords.push(tile.coord);
  }
  return coords;
}

function applyHazardResult(
  result: { tileDamage: Map<string, number>; destroyedDefenses: string[]; overwhelmedDefenses: string[] },
  overlay: HazardOverlayManager,
  now: number
): void {
  for (const key of result.destroyedDefenses) {
    const [q, r] = key.split(",").map(Number);
    defenses.destroy({ q, r });
  }
  for (const key of result.overwhelmedDefenses) {
    const inst = state.defenses.get(key);
    if (!inst) continue;
    const [q, r] = key.split(",").map(Number);
    defenses.setDegradeVisual({ q, r }, inst.degradeAmount);
  }
  for (const [key, damage] of result.tileDamage) {
    if (damage < 0.08) continue;
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    overlay.show(coord, terrain.heightAt(coord), damage, now);
  }
}

// --- Monsoon Flood telegraph + resolution ------------------------------------

const FLOOD_TELEGRAPH_COLOR = new THREE.Color("#0b2033");
const FLOOD_INTERVAL_TURNS = 15;
const FLOOD_TELEGRAPH_TURNS = 2;
let nextFloodAtTurn = FLOOD_INTERVAL_TURNS;

let floodTelegraphing = false;

function updateFloodTelegraph(): void {
  const turnsUntil = nextFloodAtTurn - state.turn;
  const telegraphing = turnsUntil > 0 && turnsUntil <= FLOOD_TELEGRAPH_TURNS;
  if (telegraphing && !floodTelegraphing) playSound("hazard_telegraph");
  floodTelegraphing = telegraphing;
  for (const coord of tilesOfType("river")) terrain.setTint(coord, telegraphing ? FLOOD_TELEGRAPH_COLOR : null);
}

/** Resolves the flood: visible in-scene (rising water, defenses absorbing/failing/degrading), not just meter numbers. */
function triggerFlood(baseSeverity: number): void {
  const result = resolveMonsoonFlood(state, baseSeverity);
  applyHazardResult(result, floodOverlay, performance.now());
  for (const coord of tilesOfType("river")) terrain.setTint(coord, null);
  floodTelegraphing = false;
  nextFloodAtTurn = state.turn + FLOOD_INTERVAL_TURNS;
  playSound("hazard_resolve");
  refreshHud();
  checkEraEnd();
}

// --- Cyclone telegraph + resolution -------------------------------------------

const CYCLONE_TELEGRAPH_COLOR = new THREE.Color("#3a3348");
const CYCLONE_INTERVAL_TURNS = 11;
const CYCLONE_TELEGRAPH_TURNS = 1; // fast — little warning, per Section 5
let nextCycloneAtTurn = CYCLONE_INTERVAL_TURNS;

function coastalCentroid(): { x: number; z: number } | null {
  const coords = tilesOfType("coast", "estuary");
  if (coords.length === 0) return null;
  let x = 0;
  let z = 0;
  for (const c of coords) {
    const w = axialToWorld(c, 1.0);
    x += w.x;
    z += w.z;
  }
  return { x: x / coords.length, z: z / coords.length };
}

let cycloneTelegraphing = false;

function updateCycloneTelegraph(): void {
  const turnsUntil = nextCycloneAtTurn - state.turn;
  const telegraphing = turnsUntil > 0 && turnsUntil <= CYCLONE_TELEGRAPH_TURNS;
  if (telegraphing && !cycloneTelegraphing) playSound("hazard_telegraph");
  cycloneTelegraphing = telegraphing;
  for (const coord of tilesOfType("coast", "estuary")) {
    terrain.setTint(coord, telegraphing ? CYCLONE_TELEGRAPH_COLOR : null, 0.45);
  }
  const centroid = coastalCentroid();
  cycloneIcon.visible = telegraphing && centroid !== null;
  if (telegraphing && centroid) cycloneIcon.position.set(centroid.x, 2.2, centroid.z);
}

/** Resolves the cyclone: wind+surge combined, Cyclone Shelter protecting Trust rather than land. */
function triggerCyclone(baseSeverity: number): void {
  const result = resolveCyclone(state, baseSeverity);
  applyHazardResult(result, cycloneOverlay, performance.now());
  for (const coord of tilesOfType("coast", "estuary")) terrain.setTint(coord, null);
  cycloneIcon.visible = false;
  cycloneTelegraphing = false;
  nextCycloneAtTurn = state.turn + CYCLONE_INTERVAL_TURNS;
  playSound("hazard_resolve");
  refreshHud();
  checkEraEnd();
}

// --- Era loop ------------------------------------------------------------------

/** Section 2: era soft-ends when Resilience hits zero — banked score, no hard game-over screen. */
function checkEraEnd(): void {
  if (!state.isEraOver) return;
  const score = Math.round(computeEraScore(state));
  const erasSoFar = state.erasCompleted + 1;
  playSound("era_end");
  hud.showBanner(`Era ${erasSoFar} retired — score ${score}. A new era begins.`);

  buildings.reset();
  defenses.reset();
  floodOverlay.reset();
  cycloneOverlay.reset();

  state.startNewEra(); // resets state.claimed back to the starting cluster
  terrain.resetClaims(keysToCoords(state.claimed));
  nextFloodAtTurn = FLOOD_INTERVAL_TURNS;
  nextCycloneAtTurn = CYCLONE_INTERVAL_TURNS;

  refreshClaimRing();
  refreshHud();
}

/** Section 2: "a slowly rising monsoon intensity / cyclone season modifier" biases future severity upward within an era. */
function rolledSeverity(): number {
  return 1.0 + Math.random() * 0.6 + state.severityBaseline;
}

/** Claims one adjacent hex (Section 2's replacement for tile-drawing): costs Coin, reveals it, counts as a turn. */
function claimTile(coord: AxialCoord): boolean {
  if (!state.claim(coord)) return false;
  terrain.claimTile(coord);
  playSound("tile_settle");

  refreshClaimRing();
  refreshHud();

  if (state.turn >= nextFloodAtTurn) triggerFlood(rolledSeverity());
  else updateFloodTelegraph();

  if (state.turn >= nextCycloneAtTurn) triggerCyclone(rolledSeverity());
  else updateCycloneTelegraph();

  return true;
}

// --- Build / defend popover --------------------------------------------------

function openBuildPopover(coord: AxialCoord): void {
  const buildingOptions: PopoverOption[] = state
    .buildableAt(coord)
    .map((d) => ({ id: d.id, name: d.name, buildCost: d.buildCost, kindLabel: "building" }));
  const defenseOptions: PopoverOption[] = state
    .buildableDefensesAt(coord)
    .map((d) => ({ id: d.id, name: d.name, buildCost: d.buildCost, kindLabel: d.category }));
  const options = [...buildingOptions, ...defenseOptions];

  if (options.length === 0) return;
  const worldTop = terrain.heightAt(coord);
  const { x: wx, z: wz } = axialToWorld(coord, 1.0);
  const screen = worldToScreen(wx, worldTop + 0.3, wz);

  buildPopover.show(screen.x, screen.y, options, state.coin, (id) => {
    if (buildingOptions.some((o) => o.id === id)) {
      if (!state.build(coord, id)) return;
      buildings.place(coord, id, terrain.heightAt(coord), { animate: true });
    } else {
      if (!state.buildDefense(coord, id)) return;
      defenses.place(coord, id, terrain.heightAt(coord), { animate: true });
    }
    playSound("build");
    refreshHud();
  });
}

// --- Input ---------------------------------------------------------------------
//
// Single source of truth for dismissal (NEXT_STEPS.md): if the popover is
// open, the first click anywhere just closes it and does nothing else — a
// second, separate click is needed to claim a tile or open a different
// tile's popover. No same-click close-and-reopen chains.

const raycaster = new THREE.Raycaster();
const pointer = new THREE.Vector2();

renderer.domElement.addEventListener("click", (event: MouseEvent) => {
  if (buildPopover.isOpen) {
    buildPopover.hide();
    return;
  }

  const rect = renderer.domElement.getBoundingClientRect();
  pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
  pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

  raycaster.setFromCamera(pointer, camera);
  const hits = raycaster.intersectObjects(terrain.raycastTargets);
  if (hits.length === 0 || hits[0].instanceId === undefined) return;

  const coord = terrain.coordForHit(hits[0].object, hits[0].instanceId);
  if (!coord) return;

  const key = `${coord.q},${coord.r}`;
  if (state.claimed.has(key)) openBuildPopover(coord);
  else if (state.isClaimable(coord)) claimTile(coord);
  // else: unclaimed and not yet reachable — no-op, matches Section 3's "no dead click" spirit.
});

start((nowMs) => {
  terrain.tick(nowMs);
  buildings.tick(nowMs);
  defenses.tick(nowMs);
  floodOverlay.tick(nowMs);
  cycloneOverlay.tick(nowMs);
  claimRing.tick(nowMs);
  if (cycloneIcon.visible) cycloneIcon.rotation.z = nowMs * 0.003;
});

/**
 * Dev-only scenario helpers (Section 10: a hidden, non-UI debug overlay is
 * explicitly sanctioned for testing). Not part of the real UI — no button,
 * no visible affordance. Triggered only via URL params.
 */
function devAutoClaim(count: number): void {
  for (let i = 0; i < count; i++) {
    const options = state.claimFrontier();
    if (options.length === 0) break;
    claimTile(options[0]);
  }
}

/** Prefers a building type not yet built anywhere, so a dev screenshot shows variety rather than one type repeated. */
function devAutoBuild(): void {
  const builtTypes = new Set<string>();
  for (const key of state.claimed) {
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    const options = state.buildableAt(coord);
    const affordable = options.filter((o) => o.buildCost <= state.coin);
    if (affordable.length === 0) continue;
    const pick = affordable.find((o) => !builtTypes.has(o.id)) ?? affordable[0];
    if (state.build(coord, pick.id)) {
      buildings.place(coord, pick.id, terrain.heightAt(coord), { animate: true });
      builtTypes.add(pick.id);
    }
  }
  refreshHud();
}

/** Prefers a defense type not yet built anywhere, so a dev screenshot shows every category at once. */
function devAutoDefend(): void {
  const builtTypes = new Set<string>();
  for (const key of state.claimed) {
    const [q, r] = key.split(",").map(Number);
    const coord = { q, r };
    const options = state.buildableDefensesAt(coord);
    const affordable = options.filter((o) => o.buildCost <= state.coin);
    if (affordable.length === 0) continue;
    const pick = affordable.find((o) => !builtTypes.has(o.id)) ?? affordable[0];
    if (state.buildDefense(coord, pick.id)) {
      defenses.place(coord, pick.id, terrain.heightAt(coord), { animate: true });
      builtTypes.add(pick.id);
    }
  }
  refreshHud();
}

const params = new URLSearchParams(location.search);
const autoclaimParam = params.get("autoclaim");
if (autoclaimParam) devAutoClaim(Number(autoclaimParam));
const coinBoost = params.get("coinboost");
if (coinBoost) {
  state.coin += Number(coinBoost);
  refreshHud();
}
if (params.has("autobuild")) devAutoBuild();
if (params.has("autodefend")) devAutoDefend();
const floodParam = params.get("flood");
if (floodParam) triggerFlood(Number(floodParam));
const cycloneParam = params.get("cyclone");
if (cycloneParam) triggerCyclone(Number(cycloneParam));
